version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/examples/*"
      - "/integration-tests/code-provider/provider"
    schedule:
      interval: "monthly"
      time: "05:00"
    assignees:
      - "pierskarsenbarg"
    ignore:
      - dependency-name: "github.com/pulumi/pulumi/pkg/v3"
      - dependency-name: "github.com/pulumi/pulumi/sdk/v3"

  - package-ecosystem: "npm"
    directories:
      - "/integration-tests/*/pulumi"
      - "/examples/*/program"
    schedule:
      interval: "monthly"
      time: "05:00"
    assignees:
      - "pierskarsenbarg"
    ignore:
      - dependency-name: "typescript"
        versions: ["7.x"]

  - package-ecosystem: "bun"
    directories:
      - "/integration-tests/api"
    schedule:
      interval: "monthly"
      time: "05:00"
    assignees:
      - "pierskarsenbarg"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      time: "05:00"
    assignees:
      - "pierskarsenbarg"
