version: 2

project_name: pulumi-openapi-provider

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "^style:"
      - "^refactor:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: pierskarsenbarg
    name: pulumi-openapi-provider
  name_template: "{{ .Tag }}"
  prerelease: auto
